import type { Metadata } from 'next'

import '@/styles/globals.css'
import { SiteHeader } from '@/components/site-header'
import { fontSans } from '@/lib/fonts'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Digital Boost',
  description: 'Generated by Digital Boost',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="light scroll-smooth">
      <body
        className={cn('bg-background font-sans antialiased', fontSans.variable)}
      >
        <div className="flex min-h-screen flex-1 flex-col">
          <SiteHeader />
          {children}
        </div>
      </body>
    </html>
  )
}
